name = "robson-cassiano-portfolio"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "robson-cassiano-portfolio-db"
database_id = "0bfffdf2-cba9-4abb-90e4-72325fb1b640"

# Service Binding: Cloudflare Email Routing Worker
[[services]]
binding = "EMAIL_ROUTER"
service = "robson-cassiano-email-router"

[vars]
ADMIN_SECRET = "robson_secret_2026"



