name = "robson-cassiano-portfolio"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Service Binding para o Worker Dedicado de Automação e Mensageria
[[services]]
binding = "CRON_PUBLISHER"
service = "robson-cassiano-cron-publisher"
