name = "robson-cassiano-cron-publisher"
main = "src/index.ts"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[triggers]
# 1. Toda Segunda-feira às 15:00 UTC (12:00 BRT): Artigo da Live mais recente
# 2. Toda Sexta-feira às 15:00 UTC (12:00 BRT): Artigo de Conteúdo Aleatório do acervo
crons = [
  "0 15 * * 1",
  "0 15 * * 5"
]

[ai]
binding = "AI"
