name = "robson-cassiano-cron-publisher"
main = "src/index.ts"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[triggers]
crons = ["0 12 * * 1"] # Toda segunda-feira às 12:00 UTC (09:00 Horário de Brasília)

[ai]
binding = "AI"
