name = "robson-cassiano-cron-publisher"
main = "src/index.ts"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[triggers]
# 1. Diariamente às 15:00 UTC (12:00 BRT): Disparo da Sequência de E-mails de 7 Dias
# 2. Segunda-feira às 15:00 UTC: Artigo da Live mais recente
# 3. Sexta-feira às 15:00 UTC: Artigo de Conteúdo Aleatório do acervo
crons = [
  "0 15 * * *",
  "0 15 * * 1",
  "0 15 * * 5"
]


[ai]
binding = "AI"
